const stores = [
    {
        id:1,
      logo_store: "",
      nom_store: "Le Délice du Souk",
      proprietaire: "Fatima Zahra",
      ville: "Tanger",
      localisation: "33.42525, -7.8",
      liste_menu: ["Bissara"],
      notation: 4.5,
      email : "Fatima.Zahra@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/bissara.jpg',
      image2:'/streetFoodImages/bissaraa.jpg',
    },
    {
        id:2,
      logo_store: "",
      nom_store: "Casa Beldi",
      proprietaire: "Karim Hassan",
      ville: "Tanger",
      localisation: "33.42525, -7.8",
      liste_menu: [
        "Chfenj"
      ],
      notation: 4.2,
      email : "Karim.Hassan@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/chfenjj.jpg',
      image2:'/streetFoodImages/chfenjjj.jpg',
    },
    {
        id:3,
      logo_store: "",
      nom_store: "PopCorn Shop",
      proprietaire: "Amina Khalil",
      ville: "Rabat",
      localisation: "33.42525, -7.8",
      liste_menu: ["PopCorn"],
      notation: 4.7,
      email : "Amina.Khalil@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/popcorn.jpg',
      image2:'/streetFoodImages/popcornn.jpg',
    },
    {
        id:4,
      logo_store: "",
      nom_store: "Casa Express",
      proprietaire: "Ahmed El Mansouri",
      ville: "Casablanca",
      localisation: "33.42525, -7.8",
      liste_menu: ["Babouch"],
      notation: 4.6,
      email : "Ahmed.ElMansouri@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/babouch.jpg',
      image2:'/streetFoodImages/babouch.jpg',
    },
    {
        id:5,
      logo_store: "",
      nom_store: "حلويات شرقية",
      proprietaire: "Nadia Benjelloun",
      ville: "Tanger",
      localisation: "33.42525, -7.8",
      liste_menu: ["Baklava"],
      notation: 4.3,
      email : "Nadia.Benjelloun@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/baklava.jpg',
      image2:'/streetFoodImages/baklavaa.jpg',
    },
    {
        id:6,
      logo_store: "",
      nom_store: "Juicy Juice",
      proprietaire: "Youssef Amrani",
      ville: "Rabat",
      localisation: "33.42525, -7.8",
      liste_menu: ["Jus"],
      notation: 4.8,
      email : "Youssef.Amrani@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/jus.jpg',
      image2:'/streetFoodImages/juss.jpg',
    },
    // by sara
    {
      id:7,
    logo_store: "",
    nom_store: "Corn Street",
    proprietaire: "Youssef Amrani",
    ville: "Casablanca",
    localisation: "33.42525, -7.8",
    liste_menu: ["Kbal"],
    notation: 4.8,
    email : "Youssef.Amrani@gmail.com",
    phone : "0677777777",
    image1:'/streetFoodImages/kbal.jpg',
    image2:'/streetFoodImages/kball.jpg',
  },{
    id:8,
  logo_store: "",
  nom_store: "Rabat Express",
  proprietaire: "Youssef Amrani",
  ville: "Rabat",
  localisation: "33.42525, -7.8",
  liste_menu: ["Café"],
  notation: 4.8,
  email : "Youssef.Amrani@gmail.com",
  phone : "0677777777",
  image1:'/streetFoodImages/cafe.jpg',
  image2:'/streetFoodImages/cafee.jpg',
},{
  id:9,
logo_store: "",
nom_store: "Riad El Medina",
proprietaire: "Youssef Amrani",
ville: "Tanger",
localisation: "33.42525, -7.8",
liste_menu: ["Thé à la menthe"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/atay.jpg',
image2:'/streetFoodImages/atayy.jpg',
},
{
  id:10,
logo_store: "",
nom_store: "Foul à la marocaine",
proprietaire: "Youssef Amrani",
ville: "Casablanca",
localisation: "33.42525, -7.8",
liste_menu: ["Foul"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/foull.jpg',
image2:'/streetFoodImages/foul.jpg',
},
{
  id:11,
logo_store: "",
nom_store: "Riad Zman",
proprietaire: "Youssef Amrani",
ville: "Casablanca",
localisation: "33.42525, -7.8",
liste_menu: ["Harira"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/hariraa.jpg',
image2:'/streetFoodImages/harira.jpg',
},{
  id:12,
logo_store: "",
nom_store: "Ruelle Gourmande",
proprietaire: "Youssef Amrani",
ville: "Rabat",
localisation: "33.42525, -7.8",
liste_menu: ["Ice Cream"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/iceCream.jpg',
image2:'/streetFoodImages/iceCreamm.jpg',
},
{
  id:13,
logo_store: "",
nom_store: "سوق الأطعمة الشعبية",
proprietaire: "Youssef Amrani",
ville: "Casablanca",
localisation: "33.42525, -7.8",
liste_menu: ["Maaqouda"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/maakouda.jpg',
image2:'/streetFoodImages/maakouda.jpg',

},{
  id:14,
logo_store: "",
nom_store: "مأكولات مغربية",
proprietaire: "Youssef Amrani",
ville: "Tanger",
localisation: "33.42525, -7.8",
liste_menu: ["Loubia"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/loubya.jpg',
image2:'/streetFoodImages/loubyaa.jpg',
},{
  id:15,
logo_store: "",
nom_store: "Dar El Benna",
proprietaire: "Youssef Amrani",
ville: "Casablanca",
localisation: "33.42525, -7.8",
liste_menu: ["Sandwich"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/sandwich.jpg',
image2:'/streetFoodImages/sandwichh.jpg',
},
{
  id:16,
logo_store: "",
nom_store: "Oleagineux du Maroc",
proprietaire: "Youssef Amrani",
ville: "Tanger",
localisation: "33.42525, -7.8",
liste_menu: ["Oléagineux"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/mokasarat.jpg',
image2:'/streetFoodImages/mokasarat.jpg',

},
{
  id:17,
logo_store: "",
nom_store: "Délices de la Rue",
proprietaire: "Youssef Amrani",
ville: "Rabat",
localisation: "33.42525, -7.8",
liste_menu: ["Crepes, Gauffres"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/crepess.jpg',
image2:'/streetFoodImages/crepes.jpg',
},
{
  id:18,
logo_store: "",
nom_store: "Le Petit Coin Gourmet",
proprietaire: "Youssef Amrani",
ville: "Casablanca",
localisation: "33.42525, -7.8",
liste_menu: ["Crepes, Gauffres"],
notation: 4.8,
email : "Youssef.Amrani@gmail.com",
phone : "0677777777",
image1:'/streetFoodImages/wafers.jpg',
image2:'/streetFoodImages/wafers.jpg',
},
  ];

export default stores;