const stores = [
    {
        id:1,
      logo_store: "",
      nom_store: "Le Délice du Souk",
      proprietaire: "Fatima Zahra",
      ville: "Casablanca",
      localisation: "33.42525, -7.8",
      liste_menu: ["Bissara"],
      notation: 4.5,
      email : "Fatima.Zahra@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/bissara.jpg',
      image2:'/streetFoodImages/bissaraa.jpg',
    },
    {
        id:2,
      logo_store: "",
      nom_store: "Marrakech Grill",
      proprietaire: "Karim Hassan",
      ville: "Tanger",
      localisation: "33.42525, -7.8",
      liste_menu: [
        "Chfenj"
      ],
      notation: 4.2,
      email : "Karim.Hassan@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/chfenjj.jpg',
      image2:'/streetFoodImages/chfenjjj.jpg',
    },
    {
        id:3,
      logo_store: "",
      nom_store: "Riad El Medina",
      proprietaire: "Amina Khalil",
      ville: "Rabat",
      localisation: "33.42525, -7.8",
      liste_menu: ["popCorn"],
      notation: 4.7,
      email : "Amina.Khalil@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/popcorn.jpg',
      image2:'/streetFoodImages/popcornn.jpg',
    },
    {
        id:4,
      logo_store: "",
      nom_store: "Casa Shawarma Express",
      proprietaire: "Ahmed El Mansouri",
      ville: "Casablanca",
      localisation: "33.42525, -7.8",
      liste_menu: ["babouch"],
      notation: 4.6,
      email : "Ahmed.ElMansouri@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/babouch.jpg',
      image2:'/streetFoodImages/babouch.jpg',
    },
    {
        id:5,
      logo_store: "",
      nom_store: "Tacos Time",
      proprietaire: "Nadia Benjelloun",
      ville: "Tanger",
      localisation: "33.42525, -7.8",
      liste_menu: ["baklawa"],
      notation: 4.3,
      email : "Nadia.Benjelloun@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/baklava.jpg',
      image2:'/streetFoodImages/baklavaa.jpg',
    },
    {
        id:6,
      logo_store: "",
      nom_store: "Kebab Royale",
      proprietaire: "Youssef Amrani",
      ville: "Rabat",
      localisation: "33.42525, -7.8",
      liste_menu: ["jus"],
      notation: 4.8,
      email : "Youssef.Amrani@gmail.com",
      phone : "0677777777",
      image1:'/streetFoodImages/juss.jpg',
      image2:'/streetFoodImages/jus.jpg',
    },
  ];

export default stores;