const stores = [
    {
        id:1,
      logo_store: "",
      nom_store: "Le Délice du Souk",
      proprietaire: "Fatima Zahra",
      ville: "Casablanca",
      localisation: "33.42525, -7.8",
      liste_menu: ["Tajine", "Brochettes", "Couscous", "Pastilla"],
      notation: 4.5,
      email : "Fatima.Zahra@gmail.com",
      phone : "0677777777",
    },
    {
        id:2,
      logo_store: "",
      nom_store: "Marrakech Grill",
      proprietaire: "Karim Hassan",
      ville: "Tanger",
      localisation: "33.42525, -7.8",
      liste_menu: [
        "Chawarma",
        "Hamburger",
        "Brochettes mixtes",
        "Thé à la menthe",
      ],
      notation: 4.2,
      email : "Karim.Hassan@gmail.com",
        phone : "0677777777",
    },
    {
        id:3,
      logo_store: "",
      nom_store: "Riad El Medina",
      proprietaire: "Amina Khalil",
      ville: "Rabat",
      localisation: "33.42525, -7.8",
      liste_menu: ["Harira", "Pastilla", "Kefta", "Makouda"],
      notation: 4.7,
        email : "Amina.Khalil@gmail.com",
        phone : "0677777777",
    },
    {
        id:4,
      logo_store: "",
      nom_store: "Casa Shawarma Express",
      proprietaire: "Ahmed El Mansouri",
      ville: "Casablanca",
      localisation: "33.42525, -7.8",
      liste_menu: ["Shawarma", "Falafel", "Hummus", "Salades variées"],
      notation: 4.6,
      email : "Ahmed.ElMansouri@gmail.com",
        phone : "0677777777",
    },
    {
        id:5,
      logo_store: "",
      nom_store: "Tacos Time",
      proprietaire: "Nadia Benjelloun",
      ville: "Tanger",
      localisation: "33.42525, -7.8",
      liste_menu: ["Tacos", "Burgers", "Fajitas", "Boissons fraîches"],
      notation: 4.3,
      email : "Nadia.Benjelloun@gmail.com",
        phone : "0677777777",
    },
    {
        id:6,
      logo_store: "",
      nom_store: "Kebab Royale",
      proprietaire: "Youssef Amrani",
      ville: "Rabat",
      localisation: "33.42525, -7.8",
      liste_menu: ["Kebab", "Pizzas", "Pâtes", "Glaces"],
      notation: 4.8,
      email : "Youssef.Amrani@gmail.com",
        phone : "0677777777",
    },
  ];

export default stores;